plugins:
  - "@typescript-eslint"
  - testing-library
env:
  browser: true
  node: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
extends:
  - eslint:recommended
  - plugin:testing-library/dom
rules:
  comma-dangle:
    - error
    - always-multiline
  consistent-return: error
  indent:
    - error
    - 4
    - SwitchCase: 1
  quotes: error
  semi: error
  keyword-spacing: error
  space-before-blocks: error
  no-multiple-empty-lines:
    - error
    - max: 1
      maxBOF: 0
      maxEOF: 0
  no-multi-spaces: error
overrides:
  - files: ["*.ts", "*.tsx"]
    parserOptions:
      project:
        - ./tsconfig.json
    extends:
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
    rules:
      indent: "off"
      semi: "off"
      no-return-await: "off"
      "@typescript-eslint/indent":
        - error
        - 4
        - SwitchCase: 1
      "@typescript-eslint/member-delimiter-style": error
      "@typescript-eslint/object-curly-spacing":
        - error
        - always
      "@typescript-eslint/return-await":
        - error
        - always
      "@typescript-eslint/semi": error
      # custom rules to fix code style
      "@typescript-eslint/require-await": "off"
      "@typescript-eslint/no-unsafe-argument": "off"
      "@typescript-eslint/no-unsafe-assignment": "off"
  - files: src/**/*
    env:
      node: false
  - files: [src/**/*.test.*, test/**/*]
    env:
      jest: true
    rules:
      "@typescript-eslint/no-non-null-assertion": "off"
      "@typescript-eslint/unbound-method": "off"

